### ISSUE TITLE
How to invoke DemoExplorer?

### ISSUE THREAD

**Issue by denisvmedia** [nightroman/FarNet#1]
I'm playing with FarNet and I'm not able to make DemoExplorer working. How is it supposed to work?
@nightroman

**Comment by nightroman** [comment]
Ah, it looks like this is not described in help.

The resource panel with its `DemoExplorer` is opened by the command is `demo: resources`.

- In the Far panel make some resource file current, e.g. *FarNet.Demo.resources* in the module directory.
- In the command line type `demo: resources`

As a result the panel showing the content of *FarNet.Demo.resources* is opened.

**Comment by denisvmedia** [comment]
It works. Thank you.
