### ISSUE TITLE
Location on launch and exit

### ISSUE THREAD

**Issue by regs01** [nightroman/FarNet#11]
Is it possible to make active panel location per active directory where far was launched. And the other way - is it possible to set location in powershell after exiting Far per path in active panel when exiting?

**Comment by nightroman** [comment]
It is possible. The first part is easy. The second is not. Here is the full example

````powershell

<#
.Synopsis
	Starts Far and manages start and exit current directory.

.Description
	Requires:
	- Far.exe is in the path
	- Far uses the default settings directory
	- get and configure System.Data.Sqlite, see
	https://github.com/nightroman/FarNet/blob/master/PowerShellFar/Bench/Connect-SQLite-.ps1
#>

# get current file system location
$CurrentDirectory = (Get-Location -PSProvider FileSystem).ProviderPath

# run Far with panels set to the current location
Far.exe /w $CurrentDirectory $CurrentDirectory

# extract active panel location from localconfig.db

# get factory
$null = [System.Reflection.Assembly]::LoadFile($env:SystemDataSQLite)
$DbProviderFactory = [System.Data.SQLite.SQLiteFactory]::Instance

# open connection
$DbConnection = $DbProviderFactory.CreateConnection()
$DbConnection.ConnectionString = "Data Source = $env:LOCALAPPDATA\Far Manager\Profile\localconfig.db"
$DbConnection.Open()

# get last active panel
$c = $DbConnection.CreateCommand()
$c.CommandText = @'
SELECT value FROM general_config WHERE key = 'Panel' AND name = 'LeftFocus'
'@
$r = $c.ExecuteScalar()
$panelName = if ($r -eq 49) {'Panel.Left'} else {'Panel.Right'}

# get last active panel folder
$c = $DbConnection.CreateCommand()
$c.CommandText = @"
SELECT value FROM general_config WHERE key = '$panelName' AND name = 'Folder'
"@
$r = $c.ExecuteScalar()
$panelPath = [System.Text.Encoding]::UTF8.GetString($r)

# set current location
Set-Location -LiteralPath $panelPath
````

**Comment by regs01** [comment]
Thanks for pointing. 

I'm a newbie in PowerShell. But after extensive Googling i came up with this.
Playing out those errors to automate module installation was most difficult part for someone who got used to try/catch.

Also seems like LeftFocus has been deprecated. But there is history.db. Last path is the one that has been in active panel when Far was closed.

Copied farnet.ps1 over to Far folder. Added Far folder to PATH. And works well.

`
# farnet.ps1

function install_pssqlite () {
  if (-not (Get-InstalledModule PSSQLite -ErrorAction SilentlyContinue)) {
    Write-Host 'Installing PSSQLite module...'
    Install-Module PSSQLite -Scope CurrentUser
  }
  if (Get-InstalledModule PSSQLite -ErrorAction SilentlyContinue) {
    Import-Module PSSQLite -ErrorAction Stop
  }
  else {
    Write-Output 'Cannot install PSSQLite module. You probabaly has to run as administrator once.'
    Exit
  }
}

$CurrentDirectory = (Get-Location -PSProvider FileSystem).ProviderPath
Far.exe /w $CurrentDirectory

Import-Module PSSQLite -ErrorAction SilentlyContinue -ErrorVariable imerror
if ($imerror) {install_pssqlite}

$database = "$env:LOCALAPPDATA\Far Manager\Profile\history.db"
$dbquery = "SELECT name FROM history ORDER BY id DESC LIMIT 1"
$dbresult = Invoke-SqliteQuery -DataSource $database -Query $dbquery -ErrorAction SilentlyContinue

Remove-Module PSSQLite

if (!$dbresult) {Exit}

$path = $dbresult.name

if (Test-Path($path)) { 
  Set-Location -LiteralPath $path 
}
`
