### ISSUE TITLE
Please tell how can I modify TabExpansion2 to complete in lowercase

### ISSUE THREAD

**Issue by ihodev** [nightroman/FarNet#14]
How can I modify [TabExpansion2](https://github.com/nightroman/FarNet/blob/master/PowerShellFar/TabExpansion2.ps1) to complete in lowercase.

```
# Now
ls . -Force -Directory

# Wanted
ls . -force -directory
```

Thanks!

**Comment by nightroman** [comment]
Let me think a little bit. I have tried some straightforward conversion and it did not work (not sure why..).

**Comment by nightroman** [comment]
We can transform the final `${*}.result` before returning it:

```powershell
for($i = 0; $i -lt ${*}.result.CompletionMatches.Count; ++$i) {
    $r = ${*}.result.CompletionMatches[$i]
    ${*}.result.CompletionMatches[$i] = New-Object System.Management.Automation.CompletionResult @(
        $r.CompletionText.ToLower()
        $r.ListItemText
        $r.ResultType
        $r.ToolTip
    )
}
${*}.result
```

There are two places where we return it (actually 3, but one is special read-only).
You may create a function doing this conversion and call it.

**Comment by ihodev** [comment]
@nightroman Wow, thanks a lot!
