### ISSUE TITLE
powershell 6 and command line defaults

### ISSUE THREAD

**Issue by AndrewSav** [nightroman/FarNet#15]
Hello Roman,

hope you are doing well. I have a couple of questions:

- I don't seem to be able to figure out how to make far use powershell 6, is this possible?
- Is it possible to have far execute powershell by default, eg _without_ the `ps:` prefix?

Many thanks,
Andrew

**Comment by nightroman** [comment]
Hi Andrew,

You are talking about the PowerShellFar module, right? It is not designed for
PowerShell Core (v6). It is built for and works with the current installed
Windows PowerShell (v2 - v5).

The PowerShellFar module commands are invoked using the prefix `ps:`, there is
no other way. These commands are invoked in the session "inside Far".

As for PowerShell apps (either v2 - v5 `powershell.exe` or v6 `pwsh.exe`),
You can run any of them using the Far command line as usual external console
applications, "outside Far".

In theory you can try to play with `COMSPEC` and set it to `powershell.exe` or
`pwsh.exe`. Then (in theory!) you can run PowerShell commands without prefix
and executable name. I never tried this and not going to. Not sure it's a
good idea, I would not like to lose the usual `CMD` commands.

Hope this helps. What are you trying to do and "have issues"?
Please ask more specific questions.

**Comment by AndrewSav** [comment]
Thank you, that's fine.

In 2019 I personally feel that CMD does not have much of utility. In the rare cases when it's required, you an drop to CMD from powershell. 

I have many powershell utility scripts that I would like to execute directly from the Far Manager command line, that is I have myscript.ps1 somewhere on PATH and I'd like to type `myscript -a b -c d` and get it executed. I have to have a separate from Far window for that (or I'll have to type ps: every time).

Similarily some of the scripts are written for powershell 6 and won't work with powershell 5, so desire is to have it at fingertips inside Far Manager - working in a single window could be more convinient when switching between two.

From your answer I understand that you have no desire of supporting or reasearching that, and that's fine, I can understand that. I thank you for the prompt answer, and for all the for you've done on PowerShellFar and FarNet.

**Comment by nightroman** [comment]
Ah, I see. Well, for running *scripts* you do not have to type `ps:` or exe name.
You have to set your associations properly, that's it.

System association:

```powershell
cmd /c ASSOC .ps1=Microsoft.PowerShellScript.1
cmd /c @"
FType Microsoft.PowerShellScript.1=$PSHOME\PowerShell.exe -NoProfile "& '%1' %*"
"@
```

Plus, add `.ps1` to `PATHEXT`, so that you can omit `.ps1` in commands.

After that, given a script `foo.ps1` in the path, you can run it as

    foo arg1 arg2 ...
    
See, not prefix, no exe name, just script name and parameters.

Alternatively you can do this using Far Associations.
But I prefer system, they work outside Far as well.

**Comment by nightroman** [comment]
By the way, I have my own helper `p6.cmd`

```cmd
@echo off
%powershell6% -NoProfile -ExecutionPolicy Bypass %*
```

where `%powershell6%` points to my `...\pwsh.exe`. Then I just type `p6 foo ...` when I need to run v6.

**Comment by AndrewSav** [comment]
Thank you for this, lot's of useful tips!
