### ISSUE TITLE
.Net Core 3+ Support

### ISSUE THREAD

**Issue by fitdev** [nightroman/FarNet#16]
Are there any plans to support .Net Core 3.0 or 3.1 instead of / in addition to .Net Framework?

**Comment by nightroman** [comment]
There are no such plans. FarNet is based on the C++/CLI layer, the actual Far Manager plugin. I am not sure that C++/CLI is well or fully supported by net core and I do not want to investigate at this moment.

Why are you asking?

**Comment by fitdev** [comment]
According to [`this blog post`](https://devblogs.microsoft.com/cppblog/an-update-on-cpp-cli-and-dotnet-core/), C++/CLI is supported on .Net Core 3.1.

The reason I asked is because I have fully switched to .Net Core from .Net Framework after 3.0 release, and many of our internal libraries are targeting strictly .Net Core. As such we could not use them with .Net Framework-based libraries.

In addition, C# 8 and above is only available on .Net Core and in general .Net Framework is no longer updated, with all the new development happening on .Net Core. Thus especially going forward it will make more and more sense to develop using .Net Core.

Hopefully you can take a look at supporting .Net core as well.

**Comment by nightroman** [comment]
Like I said, I have no such plans. Sorry to disappoint you. I do not need this yet and I am involved in many other projects.

BTW, are you sure that you cannot use net core libraries in this or slightly upgraded setup? Have you tried, what's the error? What if we build FarNet with a particular net framework like 4.7.2+ (net core friendly, I heard), will it help?

**Comment by fitdev** [comment]
I understand. I have very little C++ experience, but perhaps will try compiling the whole thing for .Net Core then. Hopefully it will be straight forward.

Unfortunately using any version of .Net Framework won't help since the .Net runtime is ultimately different (.Net Core having certain runtime features not available in .Net Framework at all, like Default Interface implementations for example). So, as I understand it FarNetMan.dll must load and host a .Net Core runtime, not .Net Framework one.

Thank you for your fast replies in any case.

**Comment by nightroman** [comment]
I think FarNet will move to net core when it becomes the mainstream and C++/CLI
support becomes mature. For the moment I cannot even create C++/CLI project for
net core as described in the link. Is it still in preview, now in VS 16.5?

For now I am closing the issue. If you decide to play with C++/CLI and net core
and have something to share or questions or need help, feel free to open new
issues or reopen this.

**Comment by jinek** [comment]
@nightroman May be it makes sense to keep this issue open, because there is bigger chance someone could implement it and it will be visible to newcomers.

**Comment by nightroman** [comment]
@jinek Yes it makes sense to keep it open, some sense, in some projects.

In my projects, I do not keep open issues that I am not going to work the coming future. This also makes some sense, helps to stay organized. Closed issues are also issues and source of information.

**Comment by nightroman** [comment]
@fitdev A bit late question. It looks like using some netstandard only libraries in FarNet is not an issue. I am playing with Microsoft.ML, for example. My FarNet module uses net472 and all works fine. Do you (we) really have to use **netcore** in FarNet?

**Comment by fitdev** [comment]
I have been developing my own libraries and projects on .Net Core for a number of years by now, and so cannot use NetStandard approach, since all my libs explicitly target .Net Core and use its functionality. Besides, .Net Core is the future, and .Net Framework is on maintenance mode. I believe with the upcoming .Net 5 especially the interop story will be very good, thus making .Net Core support easier to implement.

**Comment by nightroman** [comment]
OK, I see, you explicitly target netcore.

I agree, netcore is the future. It just has not come to FarNet yet :)

**Comment by fitdev** [comment]
Hopefully over the next year or two, it will :)

**Comment by nightroman** [comment]
FarNet 6 announcement -- <https://github.com/nightroman/FarNet/pull/25>
