### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by jinek** [nightroman/FarNet#17]
I could not find information about netcore support.
Also dotnet template for it would be great.

**Comment by denisvmedia** [comment]
https://github.com/nightroman/FarNet/issues/16

**Comment by nightroman** [comment]
@denisvmedia Thank you for the link (and the answer, in fact).

@jinek I think I should add a note somewhere that netcore is not supported and not going to be supported for a while.

**Comment by jinek** [comment]
Sorry, I think this one can be closed as duplicate.

**Comment by nightroman** [comment]
TODO Add some info to wiki, docs, etc. about not supported netcore.

**Comment by nightroman** [comment]
I added two notes to the wiki:

- https://github.com/nightroman/FarNet/wiki/FarNet
- https://github.com/nightroman/FarNet/wiki/FarNet-module-template

This is all I can really do at the moment. Like I said, when C++/CLI is officially released, supported, and battle tested in .NET Core then I will start looking at it.

**Comment by nightroman** [comment]
Hi @jinek Here is some hopefully good news - #24

**Comment by nightroman** [comment]
FarNet 6 announcement -- <https://github.com/nightroman/FarNet/pull/25>
