### ISSUE TITLE
Install/Update failed

### ISSUE THREAD

**Issue by zertyuiop** [nightroman/FarNet#18]
When trying to install / update FarNet, I get error 400 (bad request), NuGet works. Tested on Windows 10 and Windows 10 Developer Virtual Machine from Microsoft without any changes (.NET 4.8 included with system).

**Comment by nightroman** [comment]
@zertyuiop Thank you for reporting. Yes, I can see this, too. I am working on this.
NuGet retired some API that was used by the package installer code.

**Comment by nightroman** [comment]
@zertyuiop Could you please try again?

**Comment by zertyuiop** [comment]
@nightroman Installation, removal and update work normally, thanks.

**Comment by nightroman** [comment]
Great! Thanks again for reporting.
