### ISSUE TITLE
Feature Request: Support Chocolatey distribution

### ISSUE THREAD

**Issue by sirAndros** [nightroman/FarNet#19]
Hello!
It would really great, if you consider some common channels of distribution, which much simplify install and upgrade.
[Chocolatey](https://chocolatey.org/) is good example for it - you can specify dependencies which will automatically installed with you package (if them not exists already) and all your prereq are already exists in choco library.
Also, it comply with your current install method - it use nuget packages as container and then run powershell script that place files to its places. Also, they have some nice inbuild ps function like [Get-AppInstallLocation](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/extensions/chocolatey-core.extension/extensions/Get-AppInstallLocation.ps1) to place module files into Far installation folder.

_P.S. Many thanks for this plugins!_

**Comment by nightroman** [comment]
Hi @sirAndros 

Of course, "the more the merrier", yet another way of distribution would help (some users). But it's too much on my plate already. So the answer is I am not going to work on this. I just cannot.

Besides, I am not using Chocolatey and learning this new tool just for this is not tempting. Note that I am not using Chocolatey because it is not the only tool. I use scoop, for example. And some people may prefer scoop. So I would rather use scoop. But even this is not planned.

But you or somebody else can do this Chocolatey installer for yourself and others. We are the community.

Then. What's wrong with the current way of installing and updating FarNet packages? I think it is simple enough. Why don't you like it? How can we improve it?

**Comment by sirAndros** [comment]
Thanks, Roman.
Of course we are community and issue can implement somebody else, not necessarily you. And sorry if my english is rude enough to make you think that I demand this feature from you.
Scoop, winget and others is topic for another issue but "the more the merrier" suites distribution channels really well.
About current package manager:
firstly, nothing wrong with it, cmdlets is pretty forward, but if we left aside updates notification and autoupdates _(the lack of that  things also can be applied to choco too and can be easily solved via scheduled tasks manually)_, require maintain powershell module up-to-date too. If user didn't wrap "update module+update packages" with own function or something like this it's easy to forget update module itself. And the fact that module is rarely updated makes that thing worse - as it not a user habit.
Of course this is only potential issue and thus must have low priority. Of course if you won't change nuget repo and nuget.org will maintain existing urls :)

**Comment by nightroman** [comment]
> And sorry if my english is rude enough to make you think that I demand this feature from you.

That did not even cross my mind, sorry if I made this impression :) And even demanding features is normal, users ask/demand, maintainers consider/accept/reject, it's all normal.

> About current package manager: ...

Do you use the module which comes with PSF? There is the online (somewhat more reliable/up to date) variant, too. It's described in the main [README](https://github.com/nightroman/FarNet#readme). This way also does not need PSF to be installed.

I think it might be a good idea to remove this module from the package and reduce chances of being out of date (this probably happened recently when NuGet retired some API).

> Of course if you won't change nuget repo and nuget.org will maintain existing urls :)

I think we are safe here. As far as NuGet exists in its current form, of course.

**Comment by nightroman** [comment]
I created the follow up issue for removing FarPackage from PowerShellFar.

**Comment by sirAndros** [comment]
Thank you!
