### ISSUE TITLE
Can't run FarNet under latest stable/nightly Far manager build

### ISSUE THREAD

**Issue by kerberos464** [nightroman/FarNet#42]
Hello,
I'm trying to run the latest (7.0.5) FarNet package under the latest stable (3.0.6060) or nightly (3.0.6117) Far manager build. But after installing the package, Far manager is failing to start, crashing on FarNet plugin.
I have tried to install some previous FarNet version (7.0.1), but no luck either.
Windows 11 22H2 Build 22621.963.
Any help/suggestions?
Thanks in advance!
[bug_report.txt](https://github.com/nightroman/FarNet/files/10949826/bug_report.txt)
[far.mdmp.zip](https://github.com/nightroman/FarNet/files/10949827/far.mdmp.zip)

**Comment by nightroman** [comment]
Is it your first experience with installing FarNet? Did FarNet work before at all, what version? Do you have .NET SDK installed as required?

My versions (all works fine)
```
Far 3.0.6117.0
FarNet 7.0.5.0
PowerShellFar 7.0.8.0
PowerShell Core 7.3.3
```

**Comment by nightroman** [comment]
What is your dotnet version?
```
> dotnet --version
7.0.201
```

**Comment by kerberos464** [comment]
This is not the first time of using FarNet, I have used it for many years (I only use it for very convenient cmdlets autocomplete when writing Powershell scripts in the Far internal editor).
Also FarNet was working fine on this Windows installation before, then a couple months ago I tried to update FarNet to the latest version and then Far started to crash upon start. I simply deinstalled FarNet and now I returned to this problem again.
Unfortunately I don't remember what FarNet version was there.

I checked out and found out that I don't have any .NET SDK installed at all.
Now I have .NET SDK and Desktop installed, but problem is still here :(

```
> dotnet --version
7.0.201
```

```
> dotnet --info
.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```

**Comment by nightroman** [comment]
Do you have any FarNet modules? Have you upgraded them all as well?

**Comment by kerberos464** [comment]
I don't have any modules installed now. Tried to install PowerShellFar (v. 7.0.8), but nothing changed.

>Is the problem symptom the same? Any new error messages? New crash report files?

Now symptom is the same, Far crashes upon start with the same error message. New crash report files are attached.

[far.mdmp.zip](https://github.com/nightroman/FarNet/files/10956162/far.mdmp.zip)
[bug_report.txt](https://github.com/nightroman/FarNet/files/10956164/bug_report.txt)

![image](https://user-images.githubusercontent.com/686223/224673511-f8cde36c-7586-49c5-b738-bfae8d418895.png)

**Comment by nightroman** [comment]
How did you install? You have 32bit Far, right? Are you sure you get 32bit FarNet?

**Comment by kerberos464** [comment]
Yes, I use 32-bit Far.

>How did you install?

I did it as described in docs, via `Invoke-Expression (Invoke-WebRequest https://raw.githubusercontent.com/nightroman/FarNet/main/web.ps1)` and then `Install-FarPackage FarNet`.
Just checked FarNet.dll in the FarNet folder, it shows it's 32-bit.
Files FarNetMan.dll and Ijwhost.dll in the FarNet plugin subfolder are 32-bit as well.

I will check it with 64 bit Far a bit later today and let you know if it helped.

Thanks in advance for your help!

**Comment by nightroman** [comment]
I have tried to assemble and try FarNet 32 (first time for long time, I admit). I also have issues, PowerShell does not start. But in my case it print a very clear message "some dll is not found". I'll take a close look when time permits.

But in the meantime, is x64 working for you?

**Comment by kerberos464** [comment]
It works under clean x64 Far!

Maybe it's time for me to migrate to x64 Far :)

BTW, after FarNet installation I'm getting this error upon every Far start, had to click Enter to return to panels.
But after I created empty Modules subfolder under FarNet folder, this problem gone.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dmitr\Downloads\far-test\FarNet\Modules'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at FarNet.Works.ModuleLoader.LoadModules(String rootPath)
   at FarNet.Far0.Start()
```

**Comment by kerberos464** [comment]
I made some tests more and found out that the last x86 FarNet version that works fine for me is 5.9.4.
Version 6.0.0 or older makes my Far x86 to crash.

Also I need PowerShellFar module, so I installed version 5.9.5 (unfortunately, looks like versions 6.* and 7.* aren't compatible with FarNet 5.*)

If you need my help to continue investigating to fix the problem, let's do it.
Or I can close the issue because using the older FarNet version is ok for me.

Thank you.

**Comment by nightroman** [comment]
> Maybe it's time for me to migrate to x64 Far :)

Yes. For many reasons. Mainly because other products drop the support of x86. Some explicitly (MondoDB). Some maybe not even knowing (like me with FarNet 32, I do not really test it, just formally build and ship).

> BTW, after FarNet installation I'm getting this error upon every Far start, had to click Enter to return to panels.
But after I created empty Modules subfolder under FarNet folder, this problem gone.

Hmm, I'll think.

> Or I can close the issue because using the older FarNet version is ok for me.

Do not close, there is some work for me about this issue.

**Comment by nightroman** [comment]
@kerberos464 

I have fixed the loading error with missing Modules folder and another similar with Lib in just pushed FarNet 7.0.6. After that my x86 FarNet and PowerShellFar work fine. Thank you for pointing to this bug.

About your x86 problem. You say x64 works fine after installing .NET SDK but x86 does not. But did you install both x64 and x86 versions of SDK? Or just x64? You have to install .NET SDK x86 for Far x86.

**Comment by kerberos464** [comment]
> About your x86 problem. You say x64 works fine after installing .NET SDK but x86 does not. But did you install both x64 and x86 versions of SDK? Or just x64? You have to install .NET SDK x86 for Far x86.

Yes, you are right, after installing x86 .NET SDK I was able to upgrade to FarNet 7.0.6 on my Far x86.
Thank you!

**Comment by nightroman** [comment]
Great! Now we are done with issue. Enjoy v7, both its .NET 7x and PowerShell 7x are better.
