### ISSUE TITLE
HtmlToFarHelp fails on formatting inside link's body

### ISSUE THREAD

**Issue by johnd0e** [nightroman/FarNet#45]
Consider such source sample:
```md
Test 1
======

[Sample _link_](http://example.com)
```
<details><summary>html</summary>

```html
<h2>Test 1</h2>
<p><a href="http://example.com"><em>Sample</em> link</a></p>
```
</details>

This produces such hlf link: `~Sample ~@http://example.com@#link#`. (Notice that `link`-part is here outside the link. But ok.)

Now consider another sample:
```md
Test 1
======

[_Sample_ link](http://example.com)
```
<details><summary>html</summary>

```html
<h2>Test 2</h2>
<p><a href="http://example.com"><em>Sample</em> link</a></p>
```
</details>

Such input now causes an error: `Invalid or not supported HTML: Expected <a href=...>...</a>. At test2.html:2:34`

I suppose that simplest way would be just to skip any formatting in link's body.

**Comment by nightroman** [comment]
v1.3.4
