### ISSUE TITLE
Exception при загрузке

### ISSUE THREAD

**Issue by johnd0e** [nightroman/FarNet#46]
Впервые устанавил FarNet, по инструкции https://github.com/nightroman/FarNet#install-using-powershell
При запуске падает.

[bug_report.txt](https://github.com/nightroman/FarNet/files/12229343/bug_report.txt)
<details>

```
C:\Apps\Far3\Plugins>dotnet --version
7.0.306

C:\Apps\Far3\Plugins>dotnet --info
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found
```
</details>

**Comment by nightroman** [comment]
А Фар какой битности?

**Comment by johnd0e** [comment]
Far x32, SDK x64.

Сейчас попробую поставить SDK x32.
(я бы понял если бы оно просто не работало, но падать..)

**Comment by nightroman** [comment]
Увы, в этой ситуации оно падает, причем с нулевой полезной инфой.
Поэтому я сразу и "догадался", такое уже было.

**Comment by nightroman** [comment]
вот, было -- https://github.com/nightroman/FarNet/issues/42

Какие предложения, как это улучшить. Где что большими жирными буквами написать?

**Comment by nightroman** [comment]
Впрочем, вот тут явно надо добавить, что сдк нужной битности надо -- https://github.com/nightroman/FarNet#prerequisites
Сделаю.

**Comment by nightroman** [comment]
![image](https://github.com/nightroman/FarNet/assets/927533/9742b50d-e3a3-4a1a-96f6-60a07eefd6d3)

**Comment by johnd0e** [comment]
Всё получилось, спасибо.

Не в тему: что это за модуль не знаете https://github.com/sergey-rybalkin/BackgroundJobs?
Собрать я его собрал, но он не загружается.

**Comment by nightroman** [comment]
Не знаю, что это за модуль. Судя по коду, старый, не должен загружаться. Во-первых, он .NET Framework (old), а должен быть .NET Core (new net7.0). Во-вторых, сам код устарел местами, например, атрибут `Guid` больше не применяется, он должен быть параметром другого атрибута `ModuleTool`. https://github.com/sergey-rybalkin/BackgroundJobs/blob/68db7fa10fed2bde7c8f46d2432930ac036afe85/BackgroundJobsModule.cs#L16C6-L16C16
