### ISSUE TITLE
HtmlToFarHelp: увеличить интервал перед заголовками

### ISSUE THREAD

**Issue by johnd0e** [nightroman/FarNet#50]
Сейчас что до что после заголовка интервал одинаков - 1 строка.

Как правило, я каждый раз редактирую потом hlf вручную, чтобы между текстом, и последующим заголовком было две строки.

Возможно стоит сделать это настраиваемым.

**Comment by nightroman** [comment]
Наверное, мы можем добавить пару новых настроек в опции
https://github.com/nightroman/FarNet/blob/main/HelpDown/HtmlToFarHelp/README.md#conversion-options

```xml
<!--HLF:
    LinesBeforeTopic = 1;
    LinesAfterTopic = 1;
-->
```

А можно пример того, что производится и что вы делаете потом? А то, может, я иначе понимаю запрос.

**Comment by johnd0e** [comment]
1. Полноценные топики (`@Contents`) особого смысла тонко настраивать нет, поскольку на отображение это никак не влияет.
Вместо этого предлагаю их разделять двумя строками безусловно, чтобы в редакторе было нагляднее где начинается новый топик.

2. Обычные заголовки, не образующие топиков, я лично хочу разделять так же. Сделать ли это настраиваемым - решать вам.

Пример такой. 
<details>

---
Конвертер выдаёт сейчас так:
```
 GitHub renders this file as the usual Markdown and this is very good.
See also its raw Markdown for useful details including HTML comments.

 #Features#

   • §¦~Headings~@headings@
   • §¦~Emphasis~@emphasis@
```
К этому я добавляю ещё одну пустую строку перед заголовком, и получаю желаемое:
```
 GitHub renders this file as the usual Markdown and this is very good.
See also its raw Markdown for useful details including HTML comments.


 #Features#

   • §¦~Headings~@headings@
   • §¦~Emphasis~@emphasis@
```
---
</details>

3.
```html
<!--HLF:
    EmptyLinesAfterHeader = 1;
    EmptyLinesBeforeHeader = 2;
-->
```
Кстати есть и нюанс: название `EmptyLinesBeforeHeader` не совсем отражает желаемое поведение:
Дополнительный интервал **не нужен** в самом начале топика, если перед заголовком нет никакого текста.
Аналогично и в ситуации, где заголовок (например H2) непосредственно следует за другим (H1), т.е. между ними нет никакого другого текста.

4. Если вы решите реализовать детальную настройку, то хотелось иметь и другие возможности:

```html
<!--HLF:
    EmptyLinesAfterList = 0;
    EmptyLinesBeforeList = 0;
    EmptyLinesBetweenParagraphs = 0;
-->
```

**Comment by nightroman** [comment]
Все-таки примеры того, что вы предлагаете, нужны. В HLF, что сейчас, и что нужно, и какой настройкой. Ибо у вас одна терминология, у меня другая. И несколько лет я не трогал этот тул, все меня устраивает. Потому детали могу не помнить.

Не хочется мне по умолчанию делать 2 пустые строки. Никто не жалуется (вы первый), и мне больше с 1-й нравится. Но если многие поддержат 2, почему бы и нет.

**Comment by johnd0e** [comment]
Основной пример с заголовками - в моём сообщении под кнопкой Details.

Другие примеры тоже подготовлю, не проблема.

**Comment by nightroman** [comment]
Кнопку я не заметил :)

**Comment by nightroman** [comment]
v1.3.8 New options `EmptyLinesBeforeTopic`, `EmptyLinesAfterHeading`, `EmptyLinesBeforeHeading`
Пробуйте.

**Comment by johnd0e** [comment]
```md
<!--HLF:
    EmptyLinesAfterHeading = 0;
    EmptyLinesBeforeHeading = 2;
-->
# Header 1

## Header 2

Text
```
Даёт

```
@Contents
$ #Header 1#


 #Header 2#

 Text
```

1. `EmptyLinesAfterHeading = 0` не сработало
2. `EmptyLinesBeforeHeading = 2;` работает, но в моём примере граничный случай, когда заголовки идут подряд, причём первый это заголовок топика, который ещё и чертой отделяется:

![image](https://github.com/nightroman/FarNet/assets/1838643/de662750-9ce6-4036-b92c-1f7e80524eab)

В данном случае и одной пустой строки более чем достаточно. При том горизонтальная черта тоже разделитель.
В некоторых случаях я вообще убираю лишний интервал:
```
$ #Header 1#
 #Header 2#
```

**Comment by johnd0e** [comment]
Другие желательные настройки:

```md
<!--HLF:
    EmptyLinesBetweenParagraphs = 0;
    EmptyLinesAfterList = 0;
    EmptyLinesBeforeList = 0;
-->
# Header 1

Line 1

Line 2

- item 1
- item 2

Line 3
```
Хотелось бы получить в результате такой компактный текст:
```
 Line 1
 Line 2
   • §¦item 1
   • §¦item 2
 Line 3
```

**Comment by johnd0e** [comment]
До кучи ещё несколько "шашечек", о которых я упоминал (совсем давно) на форуме.

Для списков:
- опционально: пустая строка между элементами списка
- возможность подсветки нумерации/буллета
  `#1.# ...`
  `#•# ...`
- возможность указать другой символ буллета (например, для списка второго уровня)
- возможность указать другой отступ слева (например 0)

Для definition lists:
- возможность "табличного" рендеринга (с указанием в какой позиции начинается второй столбец)

**Comment by nightroman** [comment]
> EmptyLinesAfterHeading = 0 не сработало

Да, нули не поддерживаются. И пока не будут, больше переделок требуется для этого, а времени нет.

> EmptyLinesBeforeHeading = 2; работает, но в моём примере граничный случай, когда заголовки идут подряд, причём первый это заголовок топика, который ещё и чертой отделяется:

Над этим подумаю. Над остальными шашечками тоже, но со временем пока туго.

**Comment by nightroman** [comment]
Вообще, есть план переделать этот тул радикально. Он создавался во премена еще хилых процессоров и задуман/реализован был для максимальной производительности. В частности, чтобы прямо из редактора маркдауна запускать просмотр текущего топика в виде хелпа по F1, много раз по мере редактирования. Потому вся конвертация делается в одит проход, и это делает код не очень простым и пригодным для создания новых шашечек.

**Comment by nightroman** [comment]
v1.3.9 Ignore `EmptyLinesBeforeHeading` for headings after headings.
Если стало получше, то это пока все с хедерами. Остальные пожелания принял к сведению.

**Comment by nightroman** [comment]
Да, почти забыл. Дефолтные значения выбирались даже не согласно моим вкусам (хотя это трудно избежать), а так, чтобы HLF рендерирг в Фаре был как-то подобен HTML ренденингу в броузере. В первую очередь для сгенерированных HTML, конечно, без стилей или с минимальными стилями (как pandoc генерит. а не руками созданные страницы).

**Comment by nightroman** [comment]
## v1.3.10

New options `HighlightListBullet`, `HighlightListNumber`

**Comment by nightroman** [comment]
## v1.3.11

New option `ListBullet`

---
![image](https://github.com/nightroman/FarNet/assets/927533/9c7ad7c2-3f5d-449b-9230-863c3807c4ac)

**Comment by johnd0e** [comment]
> Дефолтные значения выбирались даже не согласно моим вкусам (хотя это трудно избежать), а так, чтобы HLF рендерирг в Фаре был как-то подобен HTML ренденингу в броузере.

Насколько я могу судить то в html, который выдаёт pandoc, интервал до и после заголовка заметно отличаются.
```
margin-block-end 19.92px
margin-block-start 33.6px
```

> New options `HighlightListBullet`, `HighlightListNumber`

Спасибо!

> New option `ListBullet`

Предлагаю дать возможность задавать разный символы для разных уровней.

```
  ListBullet *+-
```

**Comment by nightroman** [comment]
> Насколько я могу судить то в html, который выдаёт pandoc, интервал до и после заголовка заметно отличаются.

А если убрать стили? Предыдущий конвертер и вначале пандок не добавляли ничего от себя.

**Comment by nightroman** [comment]
> Предлагаю дать возможность задавать разный символы для разных уровней.

Да, планирую.
Но надо не так, а с разделителем, ибо любая строка может быть использована как буллет. Запятая сойдет?

**Comment by nightroman** [comment]
Например, `ListBullet = ⚠️ ☕` даст такой результат:

![image](https://github.com/nightroman/FarNet/assets/927533/a1790677-d085-4cd1-843e-47b07573fa54)

**Comment by nightroman** [comment]
## v1.3.12

`ListBullet` supports one or more strings

**Comment by johnd0e** [comment]
> А если убрать стили?

Тогда всё ровно.

**Comment by johnd0e** [comment]
> Вообще, есть план переделать этот тул радикально.

Я как-то хотел это попробовать https://pandoc.org/custom-writers.html

**Comment by nightroman** [comment]
## v1.3.13

New option `ListItemEmptyLine`

---
![image](https://github.com/nightroman/FarNet/assets/927533/d5ecd478-6974-46c0-b581-02d7a26fd1bd)

**Comment by nightroman** [comment]
На этом пока думаю закрыть тикет.
