### ISSUE TITLE
HtmlToFarHelp: нюансы со вложенными списками

### ISSUE THREAD

**Issue by johnd0e** [nightroman/FarNet#55]
```html
<ul>
<li>Внешний список
  <ul>
  <li>Вложенный список</li>
  </ul>
  Продолжение элемента внешнего списка
</li>
<li>Следующий элемент внешнего списка</li>
</ul>
```
```hlf
   • §¦Внешний список

  
       • §¦Вложенный список
  
  Продолжение элемента внешнего списка
   • §¦Следующий элемент внешнего списка
```
- Как видно, "Продолжение элемента внешнего списка" вообще выпало из списка.
- Начальная позиция "Продолжение ..." в данном примере 2, т.е. совпадает с таковой в html.
  Соответственно если начать текст с позиции 0, то и в hlf он будет стоять с начала строки, и как результат - склеится с предыдущей строкой.
- И почему-то между внешним и вложенным списком интервал 2 строки. Если убрать из исходного html некоторые переносы строк, то лишних интервалов не будет.

**Comment by nightroman** [comment]
Не уверен, что буду с этим разбираться. Нужен исходный маркдаун, а не хтмл. Хотя название продукта и HtmlToFarHelp, цель его - конвертация маркдауна в хелп.

И даже если с маркдауном те же ньюансы будут, то не уверен, что буду разбираться. Списки с вложениями и с параграфами - у меня просто не будет времени на такое.

**Comment by nightroman** [comment]
For example, this markdown, reasonably composed manually
```md
# Contents

- Внешний список

    - Вложенный список

    Продолжение элемента внешнего списка

- Следующий элемент внешнего списка
```

is converted to this reasonable HLF

```
@Contents
$ #Contents#

   • §¦Внешний список

       • §¦Вложенный список

     §¦Продолжение элемента внешнего списка

   • §¦Следующий элемент внешнего списка
```

**Comment by johnd0e** [comment]
> И даже если с маркдауном те же нюансы будут, то не уверен, что буду разбираться. Списки с вложениями и с параграфами - у меня просто не будет времени на такое.

Пример в первом сообщении был намеренно упрощён, и в действительности я столкнулся с этим именно при конвертации из маркдауна.

Предложенное вами форматирование к сожалению приведёт к тому, что элементы списков будут обрамлены ещё и в \<p\>, а в hlf соответственно разделит их дополнительной пустой строкой, что нежелательно, поскольку хочется уместить весь текст статьи на одном экране.

**Comment by nightroman** [comment]
Закрою тикет, если нет какого-то чего-то простого предложения, что можно сделать. Вложенные списки с параграфами - это сложно, некогда.

**Comment by johnd0e** [comment]
> Вложенные списки с параграфами - это сложно, некогда.

"Некогда" я могу понять, хотя тикет мог бы и открытым побыть в этом случае.
Только хочу уточнить, что никаких параграфов в моём примере нет, только голые ul+li.
Пример исходного md можно увидеть тут https://github.com/nightroman/FarNet/issues/56#issuecomment-2119022392.

Реальный же образец содержит не div а details, но сути это не меняет (details я скриптом убираю, поскольку 
HtmlToFarHelp его не понимает).

**Comment by nightroman** [comment]
Не чтобы спорить, а для понимания (нашего общего). Мой пример мд превращается в такой хтмл
```
<h1 id="contents">Contents</h1>
<ul>
<li><p>Внешний список</p>
<ul>
<li>Вложенный список</li>
</ul>
<p>Продолжение элемента внешнего списка</p></li>
<li><p>Следующий элемент внешнего списка</p></li>
</ul>
```
Параграфы есть.

**Comment by nightroman** [comment]
> "Некогда" я могу понять, хотя тикет мог бы и открытым побыть в этом случае.

Понимаю логику не закрывания не сделанного тикета. Но у меня другая бухгалтерия -- то, что не будет делаться, не должно быть открытым. Тикеты в моих проектах - это список активных задач.

**Comment by johnd0e** [comment]
> Параграфы есть.

Pandoc добавляет параграфы в случае если элементы списка разделены пустой строкой.
Мой пример по ссылке выше не содержит пустых строк, и поэтому pandoc не заключает элементы списка в параграфы.

Html из первого сообщения создан pandoc. К сожалению HtmlToFarHelp на нём спотыкается.
