### ISSUE TITLE
HtmlToFarHelp: игнорировать неподдерживаемые тэги

### ISSUE THREAD

**Issue by johnd0e** [nightroman/FarNet#56]
Такие как div, details, summary.

Их присутствие в исходном маркдаун обусловлено потребностью генерировать из него не только hlf, но и html.
Div в частности бывает необходим для того чтобы добавить информацию о стиле вложенного элемента.

В настоящий момент перед конвертацией в hlf удаляю всё неподдерживаемое скриптом.

**Comment by nightroman** [comment]
Быстро попробовал кое-что. Просто игнорировать не очень хорошо получается. Могу попробовать заменять обработку на аналогичную `<p>`.

**Comment by johnd0e** [comment]
```md
1. First element
   <details><summary>Spoiler</summary>

   _Here is a lot of text_
   </details>
2. Second element
```
Это конечно же для md и html, но исходник общий.
Само собой, что в hlf не получится сделать спойлер, поэтому просто игнорируем тэги, и получаем plain text.
Я делаю это скриптом, собственно могу и продолжать дальше.

**Comment by johnd0e** [comment]
Например, мне для html нужно использовать какой-то класс для DL, или другого элемента, для которого pandpoc не позволяет задать аттрибуты напрямую

```md
:::some_class
term
:	definition
:::
```

Таким образом элемент оборачивается в дополнительный Div, и для html всё хорошо, а для hlf конвертер спотыкается.
Достаточно же просто проигнорировать тэги.

Были в практике и другие случаи, когда мне нужны были в маркдауне Div.

**Comment by nightroman** [comment]
А `<summary>Spoiler</summary>` допускает внутри форматирование? Как будете действовать для болд, италик, код?

**Comment by nightroman** [comment]
Посмотрю, что можно сделать. Не лежит душа к этому, это кроличья нора.

Вот в вашем примере `_Here is a lot of text_` при конвертации в хтмл становится италик, да? А, вот, почему? Мне было бы логичнее, что все, что внутри `<details>...</details>` должно быть интерпретировано как хтмл, а не смесь маркдауна и хтмл. И не италик я бы ожидал, а то, что вы написали для хтмл с подчеркиваниями.

**Comment by nightroman** [comment]
А, `:::some_class` и т.п. - это и был пример div, да? Это надо особой командой пандока конвертировать? Мой привычный способ конвертации этого не понимает.

**Comment by johnd0e** [comment]
> Это надо особой командой пандока конвертировать?

Это называется [fenced divs](https://pandoc.org/chunkedhtml-demo/8.18-divs-and-spans.html), и вроде как по умолчанию работает.

**Comment by johnd0e** [comment]
> Примеры ваши div в маркдауне нужны тоже.

Например, я скриптом вставляю в конец каждой статьи div, содержащий ссылки на другие разделы.
Div - потому что может содержать другие блочные элементы, иначе можно было бы использовать параграф.
Без Div тоже можно было бы, но по логике скрипта проще работать с одним элементом, чем с переменных их количеством.

Повторюсь: это и сейчас не проблема, избавиться от div в том же скрипте позже (что я сейчас [и делаю](https://forum.farmanager.com/viewtopic.php?p=177959#p177959)).

Ещё пример, когда может понадобиться div:
```md
# Contents

- Внешний список
  <div>
  - Вложенный список
  </div>
  Продолжение элемента внешнего списка
- Следующий элемент внешнего списка
```
Но это искусственный пример, а на практике у меня такая ситуация была с \<details\> (#55)

**Comment by nightroman** [comment]
Честно попробовал некоторые варианты того, что можно сделать, не влезая в дебри. Не получается удовлетворительный результат, закрываю этот тикет. Просто "игнорировать теги" не работает. Ибо с этими тегами, внутри них, в хтмл получается не то же самое, как если бы тегов не было. И результаты в HLF получаются негодные.

Теги эти не поддерживаются. Пост-обработка скриптом, что вы применяете, это не идеальное, но нормальное решение.

**Comment by johnd0e** [comment]
> Пост-обработка скриптом, что вы применяете, это не идеальное, но нормальное решение

> Просто "игнорировать теги" не работает.

Но ведь это буквально то что я делаю скриптом!

> Ибо с этими тегами, внутри них, в хтмл получается не то же самое, как если бы тегов не было.

Не могли бы вы проиллюстрировать такой случай  примером?

**Comment by nightroman** [comment]
1.md
```md
<details>
<summary>
text in `summary`
</summary>
text in `details`
</details>
```

result
```html
</head>
<body>
<details>
<summary>
text in `summary`
</summary>
text in `details`
</details>
</body>
</html>
```

**Comment by nightroman** [comment]
2.md
```md
text in `summary`

text in `details`
```

result
```html
</head>
<body>
<p>text in <code>summary</code></p>
<p>text in <code>details</code></p>
</body>
</html>
```

**Comment by johnd0e** [comment]
@nightroman 

А для чего вы изымаете теги из исходного md-файла?
HtmlToFarHelp работает не с ним, а с html, поэтому и речь идёт о том, чтобы игнорировать неподдерживаемые теги там, и только там.

И в данном случае корректный исходник (где и в summary и в details подразумевается markdown) выглядеть должен так:
```md
<details>
<summary>

text in `summary`
</summary>

text in `details`
</details>
```

```html
<details>
<summary>
text in <code>summary</code>
</summary>
text in <code>details</code>
</details>
```

И если игнорировать теги то:
```html
text in <code>summary</code>
text in <code>details</code>
```

**Comment by nightroman** [comment]
> А для чего вы изымаете теги из исходного md-файла?

Я этого не делаю. Я привел примеры хтмл, которые получаются из мд и которые потом конвертируются.
"Добавлять пустую строку, чтобы ..." - не нравится мне это.

Извините, что не оправдываю ваши надежды, но я решил поддержкой этих тегов не заниматься.
Тому есть причины, разные, в том числе и результаты проведенной работы в надежде помочь вам.

**Comment by johnd0e** [comment]
P.S.

> И в данном случае корректный исходник (где и в summary и в details подразумевается markdown) выглядеть должен так:

Не знаю почему, но у меня сейчас даже ваш исходник (где пустой строки перед текстом нет) приводит к тому же результату, т.е. маркдаун всё равно парсится.
В любом случае, в контексте данного обсуждения это непринципиально, поскольку мы обсуждаем меняется ли что-то от игнорирования неподдерживаемых тегов. И оно не меняется - в обоих случаях.

> Извините, что не оправдываю ваши надежды

Это как раз ничего, независимо от ваших мотивов. Я сейчас пытаюсь добиться лишь того, чтобы мы одинаково вопрос понимали.

> "Добавлять пустую строку, чтобы ..." - не нравится мне это.

Мне это тоже в своё время сильно не понравилось, по причине того, что я много времени потерял, разбираясь как же использовать эти тэги на Гитхабе. Но такой уж там парсер, и пришлось приноровиться. Кто-то другой может и не пользуется, ну что ж.

Но повторюсь: это всё хоть и интересно не связано с нашей темой.
Pandoc раньше мог парсить так, а в новой версии может иначе, а от наличия каких-то опций ещё и третьим образом, это всё понятно.

Главное другое: в результирующем html и hlf это должно быть однотипно.
Их ваших примеров следует что
- в одном случае будет `text` и в html и соответственно в hlf.
- в другом \<code\>text\</code\> и тоже в обоих случаях одинаково.

Очевидно, что результат должен соответствовать замыслу автора, и надо ли вставлять пустую строку там или нет - это забота автора. Если не вставил - значит таков его замысел.

Опять же - использовать или не использовать те или иные конструкции, это тоже решать автору. Вот вам какие-то странные нюансы не нравятся, и вы решаете не использовать, ваше право.

Что я пытаюсь показать: спотыкаясь на каких-то тегах HtmlToFarHelp никому не помогает.
Если этот неподдерживаемый тег встретился, значит он зачем-то нужен (в html), и попытаться продолжить обработку - более дружелюбное поведение.

Да, нужно вывести предупреждение в консоль при этом. Или строже: требовать от пользователя для подтверждения своих намерений запускать конвертер с ключом `ignore-unsupported-tags`. Или даже требовать поимённого перечисления таких тэгов.

**Comment by nightroman** [comment]
Я пробовал просто игнорировать, естественно. В результате в хлф получается какое-то непредсказуемое и неожиданное количество лишних пустых строк. Это вам надо? Нет, у вас уже было несколько тикетов по убиранию пустых строк. Поэтому я не могу такое выложить, знаю, что результат негодный.

Уже сказано, просто игнорировать недостаточно. Разбираться, что делать - это бесконечная кроличья нора, с учетом прихотей пандока, нюансов форматирования, наличия хитрых триков типа пустых строк и т.п.

**Comment by johnd0e** [comment]
> Я пробовал просто игнорировать, естественно.

Я убираю скриптом, но на результат это не влияет.

> В результате в хлф получается какое-то непредсказуемое и неожиданное количество лишних пустых строк.

В описанных мною выше случаях ничего подобного не происходит. За исключением нюанса из соседнего issue (и там не с пустыми строками проблема).

> Уже сказано, просто игнорировать недостаточно.

В большинстве случаев (моей практики) достаточно. Пусть это было и не безусловно, а по отдельному ключу командной строки, но это дало бы пользователям больше возможностей, не прибегая к необходимости использования скриптов.

Лично я всё равно скрипты использую, поэтому меня устраивает и текущее положение вещей.

**Comment by johnd0e** [comment]
> Мне было бы логичнее, что все, что внутри <details>...</details> должно быть интерпретировано как хтмл, а не смесь маркдауна и хтмл.

Оказывается работа с тэгами чётко прописана со всеми нюансами https://github.github.com/gfm/#html-block
